const fs = require('fs');
const path = require('path');

async function testUpload() {
    // Only available in Node 18+
    if (!global.fetch) {
        console.error("This script requires Node.js 18+ with native fetch API.");
        return;
    }

    // 1. Signup/Login to get token (using a new user each time to avoid conflict)
    const randomSuffix = Math.floor(Math.random() * 100000);
    const email = `testuser${randomSuffix}@example.com`;
    const password = 'TestUser123!@#'; 

    console.log(`Registering user: ${email}`);

    let token = '';

    try {
        const signupRes = await fetch('http://localhost:3000/auth/signup', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                name: 'Test User',
                email: email,
                password: password
            })
        });

        if (!signupRes.ok) {
            const text = await signupRes.text();
            console.error(`Signup failed: ${signupRes.status} ${text}`);
            return;
        }

        const signupData = await signupRes.json();
        token = signupData.token;
        console.log('Signup successful, got token.');
    } catch (e) {
        console.error('Network error during signup:', e);
        return;
    }

    // 2. Upload PDF file for conversion to DOCX
    // Use the PDF created in previous step if available, or create a dummy PDF.
    // I'll use the one I saw in uploads: 1771197261348-5748d9f6fe1eee2f-hello.pdf
    // But I don't know the full path reliably.
    // I'll just use a small PDF if I can make one, or use a sample PDF.
    // I'll check if there is a sample PDF in `node_modules` or `test_output.pdf` generated by test_libre.js
    
    const inputPath = path.join(__dirname, 'test_output.pdf');
    
    if (!fs.existsSync(inputPath)) {
        console.error(`Input file not found: ${inputPath}. Please run test_libre.js first.`);
        return;
    }

    const fileContent = fs.readFileSync(inputPath);
    const blob = new Blob([fileContent], { type: 'application/pdf' });
    
    const formData = new FormData();
    formData.append('file', blob, 'hello.pdf');
    formData.append('convertTo', 'docx');

    console.log('Uploading PDF for conversion to DOCX...');

    try {
        const response = await fetch('http://localhost:3000/files/upload', {
            method: 'POST',
            body: formData,
            headers: {
                'Authorization': `Bearer ${token}`
            }
        });

        console.log(`Status: ${response.status} ${response.statusText}`);
        const text = await response.text();
        console.log(`Response: ${text}`);

    } catch (err) {
        console.error('Upload failed:', err);
    }
}

testUpload();
